services:
  bot:
    image: gg
    environment:
        TZ: ${TZ}
    volumes:
      - ./data:/app/data:rw
      - ./data/cache/go-ytdlp:/root/.cache/go-ytdlp:rw
      - ./config.toml:/app/gachigazer.toml:ro

  duckai:
    image: ghcr.io/muratoffalex/duckai:latest
    working_dir: /app/data
    environment:
        TZ: ${TZ}
    expose:
      - "8080"
    volumes:
      - ./data:/app/data:rw
